version: '2'
services:
  mysql:
    container_name: bi_mysql
    extends:
      file: mysql.yml
      service: mysql
    networks:
      - bi-net
  minio:
    container_name: bi_minio
    extends:
      file: minio.yml
      service: minio
    networks:
      - bi-net
networks:
  bi-net:
