version: '2'
services:
  mysql:
    container_name: bi_mysql
    extends:
      file: mysql.yml
      service: mysql
    networks:
      - bi-net
  minio:
    container_name: bi_minio
    extends:
      file: minio.yml
      service: minio
    networks:
      - bi-net
  etcd:
    container_name: milvus-etcd
    extends:
      file: milvus.yml
      service: etcd
    networks:
      - bi-net
  milvus-standalone:
    container_name: milvus-standalone
    extends:
      file: milvus.yml
      service: milvus-standalone
    networks:
      - bi-net
networks:
  bi-net:
