version: '2'
services:
  minio:
    image: minio/minio
    volumes:
      - ./data/minio/data:/data
      - ./data/minio/config:/root/.minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
      - MINIO_REGION=cn-north-1
      - TZ=Asia/Shanghai
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
  init-bucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 admin admin123;
      mc mb public;
      mc anonymous set public public;
      echo 'Bucket initialized successfully'
      "